HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Controllers/ContactController.cs
namespace HashtagIT.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using HashtagIT.Common;
    using HashtagIT.Data.Common.Repositories;
    using HashtagIT.Data.Models;
    using HashtagIT.Services.Messaging;
    using HashtagIT.Web.ViewModels.Contact;
    using Microsoft.AspNetCore.Mvc;

    public class ContactController : Controller
    {
        private readonly IEmailSender emailSender;

        private readonly IRepository<ContactEntry> contactRepository;

        public ContactController(IEmailSender emailSender, IRepository<ContactEntry> contactRepository)
        {
            this.contactRepository = contactRepository;
            this.emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            viewModel.IsValid = true;

            var contactFormEntry = new ContactEntry
            {
                FullName = viewModel.FullName,
                Email = viewModel.Email,
                Subject = viewModel.Subject,
                Content = viewModel.Content,
            };
            await this.contactRepository.AddAsync(contactFormEntry);
            await this.contactRepository.SaveChangesAsync();
            await this.emailSender.SendEmailAsync(viewModel.Email, viewModel.FullName, GlobalConstants.SystemEmail, viewModel.Subject, viewModel.Content);
            this.TempData.Add("Message", "Email Has Been Sent Successfully");
            return this.Redirect("/");
        }
    }
}

HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Controllers/IGController.cs
namespace HashtagIT.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using HashtagIT.Data.Models;
    using HashtagIT.Services.Data;
    using HashtagIT.Web.ViewModels.IG;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class IGController : Controller
    {
        private readonly IIGService iGService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly API api;

        public IGController(IIGService iGService, UserManager<ApplicationUser> userManager, API api)
        {
            this.iGService = iGService;
            this.userManager = userManager;
            this.api = api;
        }

        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel, string guest)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (guest != null)
            {
                await this.iGService.Login(userId, "system", string.Empty);
                return this.RedirectToAction(nameof(this.IGIndex));
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            string phone;
            try
            {
                phone = await this.iGService.Login(userId, viewModel.IGUserName, viewModel.Password);
            }
            catch (System.Exception)
            {
                return this.RedirectToAction(nameof(this.Login));
            }

            string encryptedPassword = Cipher.Encrypt(viewModel.Password, viewModel.IGUserName);

            viewModel.Phone = phone;
            viewModel.Password = encryptedPassword;
            viewModel.UserId = userId;

            if (phone != string.Empty)
            {
                return this.RedirectToAction(nameof(this.TwoFactor), viewModel);
            }

            return this.RedirectToAction(nameof(this.IGIndex));
        }

        public IActionResult TwoFactor(LoginViewModel loginView, bool post = false)
        {
            return this.View(loginView);
        }

        [HttpPost]
        public async Task<IActionResult> TwoFactor(LoginViewModel viewModel)
        {
            var result = await this.iGService.TwoFactor(viewModel.IGUserName, viewModel.Password, viewModel.Code, viewModel.UserId);

            if (!result)
            {
                return this.RedirectToAction(nameof(this.Login));
            }

            return this.RedirectToAction(nameof(this.IGIndex));
        }

        public IActionResult IGIndex()
        {
            var userId = this.userManager.GetUserId(this.User);
            if (this.api.GetInstance(userId) == null)
            {
                return this.RedirectToAction(nameof(this.Login));
            }

            var model = this.iGService.TopHashtags();
            return this.View(model);
        }

        [HttpPost]
        public IActionResult TopNine(string username)
        {
            return this.RedirectToAction(nameof(this.TopNineResult), new { username });
        }

        public async Task<IActionResult> TopNineResult(string username)
        {
            var userId = this.userManager.GetUserId(this.User);
            TopNineViewModel viewModel = await this.iGService.TopNine(userId, username);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult NotFollowingPost(string username)
        {
            return this.RedirectToAction(nameof(this.NotFollowing), new { username });
        }

        public async Task<IActionResult> NotFollowing(string username)
        {
            var userId = this.userManager.GetUserId(this.User);
            NotFollowingViewModel viewModel = await this.iGService.NotFollowinBack(userId, username);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult FriendshipPost(string username)
        {
            return this.RedirectToAction(nameof(this.Friendship), new { username });
        }

        public async Task<IActionResult> Friendship(string username)
        {
            var userId = this.userManager.GetUserId(this.User);
            FriendshipViewModel viewModel = await this.iGService.Friendship(userId, username);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult GenerateSetPost(string hashtag)
        {
            return this.RedirectToAction(nameof(this.Friendship), new { hashtag });
        }

        public async Task<IActionResult> GenerateSet(string hashtag)
        {
            var userId = this.userManager.GetUserId(this.User);
            var model = await this.iGService.GenerateSet(userId, hashtag);
            return this.View(model);
        }
    }
}

HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using HashtagIT.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@GlobalConstants.SystemName</title>
    <link href="~/css/Instagram.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/agency.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/loader.css" rel="stylesheet" asp-append-version="true"/>  
    <link href="~/css/NotFound.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

    @Html.Raw(JavaScriptSnippet.FullScript)
</head>

<body>
    <nav class="navbar-expand-lg navbar-dark" id="mainNav" style="background-color:#212529">
        <div class="container" style="">
            <button class="navbar-toggler" type="button" data-target="#navbarResponsive">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="navbar-collapse collapse">
                <a class="navbar-brand" href="/">@GlobalConstants.SystemName</a>
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="/#tools">Tools</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" asp-controller="IG" asp-action="IGIndex">Instagram</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" asp-controller="Contact" asp-action="Index">Contact</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="container">
        @this.RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4">
                    <span class="copyright">Copyright&copy; @GlobalConstants.SystemName 2020</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li class="list-inline-item">
                            <a href="https://www.instagram.com/damian.ivanovv">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://twitter.com/Damian_Iv">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/Dam1aan">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/damian-ivanov-5b1327176/">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li class="list-inline-item">
                            <a href="/Home/Privacy">Privacy Policy</a>
                        </li>
                        <li class="list-inline-item">
                            <i class="fab fa-github"></i>
                            <a href="https://github.com/damianivanov/SoftUni-HashtagIT">Open Source</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/agency-static.js" asp-append-version="true"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/agency-static.js" asp-append-version="true"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @this.RenderSection("Scripts", required: false)
</body>
</html>

HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Views/Shared/_NavBar.cshtml
@using HashtagIT.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/agency.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>




</head>

<body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">@GlobalConstants.SystemName</a>
            <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="navbar-collapse collapse" id="navbarResponsive" style="">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#tools">Tools</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" asp-controller="Contact" asp-action="Index">Contact</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @this.RenderBody()

    <footer class="footer">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4">
                    <span class="copyright">Copyright&copy; @GlobalConstants.SystemName 2020</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li class="list-inline-item">
                            <a href="https://www.instagram.com/damian.ivanovv">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://twitter.com/Damian_Iv">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/Dam1aan">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/damian-ivanov-5b1327176/">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li class="list-inline-item">
                            <a href="/Home/Privacy">Privacy Policy</a>
                        </li>
                        <li class="list-inline-item">
                            <i class="fab fa-github"></i>
                            <a href="https://github.com/damianivanov/SoftUni-HashtagIT">Open Source</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/agency.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/agency.min.js" asp-append-version="true"></script>
    </environment>
    @this.RenderSection("Scripts", required: false)
</body>
</html>