HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Controllers/HashtagSetController.cs
namespace HashtagIT.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using HashtagIT.Common;
    using HashtagIT.Data.Common.Repositories;
    using HashtagIT.Data.Models;
    using HashtagIT.Services.Data;
    using HashtagIT.Web.ViewModels;
    using HashtagIT.Web.ViewModels.HashtagSets;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class HashtagSetController : Controller
    {
        private const int SetsPerPage = 5;
        private readonly IHashtagSetsService hashtagSetsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICategoriesService categoriesService;

        public HashtagSetController(IHashtagSetsService hashtagSetsService, UserManager<ApplicationUser> userManager, ICategoriesService categoriesService)
        {
            this.hashtagSetsService = hashtagSetsService;
            this.userManager = userManager;
            this.categoriesService = categoriesService;
        }

        public IActionResult Index()
        {
            return this.RedirectToAction(nameof(this.MySets));
        }

        public IActionResult Create()
        {
            var categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            var viewModel = new HashtagSetCreateInputModel
            {
                Categories = categories,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(HashtagSetCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.hashtagSetsService.CreateAsync(inputModel.Text, user.Id, inputModel.CategoryId, inputModel.IsPrivate);
            return this.RedirectToAction("MySets");
        }

        public IActionResult ById(int id)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (this.hashtagSetsService.IsOwner(id, userId) || this.User.IsInRole("Moderator"))
            {
                var hashtagViewModel = this.hashtagSetsService.GetById<HashtagSetViewModel>(id);
                if (hashtagViewModel != null)
                {
                    return this.View(hashtagViewModel);
                }
            }

            return this.View("Error");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (this.hashtagSetsService.IsOwner(id, userId) || this.User.IsInRole("Moderator"))
            {
                await this.hashtagSetsService.DeleteByIdAsync(id, userId);
            }

            return this.RedirectToAction("MySets");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.View("Error");
            }

            var userId = this.userManager.GetUserId(this.User);
            var viewModel = this.hashtagSetsService.GetById<HashtagSetCreateInputModel>(id.Value);
            viewModel.Categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            if (id.HasValue && (this.hashtagSetsService.IsOwner(id.Value, userId) || this.User.IsInRole("Moderator")))
            {
                return this.View(viewModel);
            }

            return this.View("Error");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(HashtagSetCreateInputModel viewModel)
        {
            if (this.ModelState.IsValid)
            {
                await this.hashtagSetsService.EditAsync(viewModel.Text, viewModel.CategoryId, viewModel.IsPrivate, viewModel.Id);
                return this.RedirectToAction(nameof(this.ById), new { id = viewModel.Id });
            }

            viewModel.Categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            return this.View(viewModel);
        }

        public async Task<IActionResult> MySets(int page = 1)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var hashtagSets = this.hashtagSetsService.GetAllByUser<HashtagSetViewModel>(user.Id, SetsPerPage, (page - 1) * SetsPerPage);
            var allPrivatePosts = this.hashtagSetsService.GetCountPrivate(user.Id);
            var viewModel = new AllHashtagSetsByUserViewModel
            {
                PagesCount = (int)Math.Ceiling((double)allPrivatePosts / SetsPerPage),
                HashtagSets = hashtagSets,
                UserName = user.UserName,
            };
            if (viewModel.PagesCount == 0)
            {
                viewModel.PagesCount = 1;
            }

            viewModel.CurrentPage = page;

            return this.View(viewModel);
        }

        public IActionResult Public(int page = 1)
        {
            var hashtagSets = this.hashtagSetsService.GetPublic<HashtagSetViewModel>(SetsPerPage, (page - 1) * SetsPerPage);
            var allPublicPosts = this.hashtagSetsService.GetCountPublic();
            var viewModel = new AllPublicHashtagSetsViewModel
            {
                PagesCount = (int)Math.Ceiling((double)allPublicPosts / SetsPerPage),
                HashtagSets = hashtagSets,
            };
            if (viewModel.PagesCount == 0)
            {
                viewModel.PagesCount = 1;
            }

            viewModel.CurrentPage = page;

            return this.View(viewModel);
        }
    }
}

HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Controllers/HomeController.cs
namespace HashtagIT.Web.Controllers
{
    using System.Diagnostics;
    using System.Threading.Tasks;

    using HashtagIT.Common;
    using HashtagIT.Data.Common.Repositories;
    using HashtagIT.Data.Models;
    using HashtagIT.Services.Messaging;
    using HashtagIT.Web.ViewModels;
    using HashtagIT.Web.ViewModels.Contact;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Controllers/IGController.cs
namespace HashtagIT.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using HashtagIT.Data.Models;
    using HashtagIT.Services.Data;
    using HashtagIT.Web.ViewModels.IG;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class IGController : Controller
    {
        private readonly IIGService iGService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly API api;

        public IGController(IIGService iGService, UserManager<ApplicationUser> userManager, API api)
        {
            this.iGService = iGService;
            this.userManager = userManager;
            this.api = api;
        }

        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel, string guest)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (guest != null)
            {
                await this.iGService.Login(userId, "system", string.Empty);
                return this.RedirectToAction(nameof(this.IGIndex));
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            string phone;
            try
            {
                phone = await this.iGService.Login(userId, viewModel.IGUserName, viewModel.Password);
            }
            catch (System.Exception)
            {
                return this.RedirectToAction(nameof(this.Login));
            }

            string encryptedPassword = Cipher.Encrypt(viewModel.Password, viewModel.IGUserName);

            viewModel.Phone = phone;
            viewModel.Password = encryptedPassword;
            viewModel.UserId = userId;

            if (phone != string.Empty)
            {
                return this.RedirectToAction(nameof(this.TwoFactor), viewModel);
            }

            return this.RedirectToAction(nameof(this.IGIndex));
        }

        public IActionResult TwoFactor(LoginViewModel loginView, bool post = false)
        {
            return this.View(loginView);
        }

        [HttpPost]
        public async Task<IActionResult> TwoFactor(LoginViewModel viewModel)
        {
            var result = await this.iGService.TwoFactor(viewModel.IGUserName, viewModel.Password, viewModel.Code, viewModel.UserId);

            if (!result)
            {
                return this.RedirectToAction(nameof(this.Login));
            }

            return this.RedirectToAction(nameof(this.IGIndex));
        }

        public IActionResult IGIndex()
        {
            var userId = this.userManager.GetUserId(this.User);
            if (this.api.GetInstance(userId) == null)
            {
                return this.RedirectToAction(nameof(this.Login));
            }

            var model = this.iGService.TopHashtags();
            return this.View(model);
        }

        [HttpPost]
        public IActionResult TopNine(string username)
        {
            return this.RedirectToAction(nameof(this.TopNineResult), new { username });
        }

        public async Task<IActionResult> TopNineResult(string username)
        {
            var userId = this.userManager.GetUserId(this.User);
            TopNineViewModel viewModel = await this.iGService.TopNine(userId, username);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult NotFollowingPost(string username)
        {
            return this.RedirectToAction(nameof(this.NotFollowing), new { username });
        }

        public async Task<IActionResult> NotFollowing(string username)
        {
            var userId = this.userManager.GetUserId(this.User);
            NotFollowingViewModel viewModel = await this.iGService.NotFollowinBack(userId, username);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult FriendshipPost(string username)
        {
            return this.RedirectToAction(nameof(this.Friendship), new { username });
        }

        public async Task<IActionResult> Friendship(string username)
        {
            var userId = this.userManager.GetUserId(this.User);
            FriendshipViewModel viewModel = await this.iGService.Friendship(userId, username);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult GenerateSetPost(string hashtag)
        {
            return this.RedirectToAction(nameof(this.Friendship), new { hashtag });
        }

        public async Task<IActionResult> GenerateSet(string hashtag)
        {
            var userId = this.userManager.GetUserId(this.User);
            var model = await this.iGService.GenerateSet(userId, hashtag);
            return this.View(model);
        }
    }
}

HashtagIT/ASP.NET Core/Web/HashtagIT.Web/Views/Home/Index.cshtml
@{
    this.Layout = "~/Views/Shared/_NavBar.cshtml";
}

@if (TempData["Message"]!=null)
{

    <div class="container-sm alert alert-success text-center" id="alert">
        @TempData["Message"]
    </div>
}

<header class="masthead img-fluid">
    <div class="container">
        <div class="intro-text">
            <div class="intro-heading m-2" id="mineTitle" style="color:azure; font-size:75px;">Welcome to HashtagIT</div>
            <div class="intro-lead-in"><i class="fas fa-angle-double-down"></i></div>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#tools">Tell Me More</a>
        </div>
    </div>
</header>



<!-- Tools -->
<section class="page-section" id="tools">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">Tools</h2>
                <h3 class="section-subheading text-muted">Tools to help you improve your instagram engagement</h3>
            </div>
        </div>
        <div class="row text-center">
            <!--Sets-->
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <a asp-controller="HashtagSet" asp-action="MySets">
                        <i class="fas fa-circle fa-stack-2x text-primary"></i>
                        <i class="fas fa-sticky-note fa-stack-1x fa-inverse"></i>
                    </a>
                </span>
                <h4 class="service-heading">Hashtag Sets</h4>
                <p class="text-muted">Place to save and manage your favorite sets of hashtags. Make them public or private and choose the best category they fit in.</p>
            </div>
            <!--Instagram-->
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <a asp-controller="IG" asp-action="IGIndex">
                        <i class="fas fa-circle fa-stack-2x text-primary"></i>
                        <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                    </a>
                </span>
                <h4 class="service-heading">Instagram Tools</h4>
                <p class="text- muted">See your mutual followers, Top Nine posts and so much more.</p>
            </div>
            <!--Forum for Sets-->
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <a asp-controller="HashtagSet" asp-action="Public">
                        <i class="fas fa-circle fa-stack-2x text-primary"></i>
                        <i class="fas fa-users fa-stack-1x fa-inverse"></i>
                    </a>
                </span>
                <h4 class="service-heading">Public Hashtags</h4>
                <p class="text-muted">Share and Vote for your favorite Hashtag Sets.</p>
            </div>
        </div>
    </div>
    <br />
</section>

<!-- Portfolio Grid -->
<section class="bg-light page-section p-0" id="portfolio">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/img/Vitosha.jpg" alt="First slide" id="mineImg">
                </div>
                <div class="carousel-item">
                    <img src="~/img/Belintash.jpg" alt="Second slide" id="mineImg">
                </div>
                <div class="carousel-item">
                    <img src="~/img/NDK.jpg" alt="Third slide" id="mineImg">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
</section>  

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Plugin JavaScript -->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Contact form JavaScript -->
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

<!-- Custom scripts for this template -->
<script src="js/agency.min.js"></script>

@section Scripts{

    <script>
        $(window).scroll(function () {
            if ($(this).scrollTop() > 0) {
                $('#alert').fadeOut();
            }
        });
    </script>
}